### ISSUE TITLE
Hello World for GenAI package

### ISSUE THREAD

**Issue by charlieforward9** [VisualPT/flutter-mediapipe-template#1]
Code example (and collaboratively the guide) for https://ai.google.dev/edge/mediapipe/solutions/genai/llm_inference that runs on Android OS

**Comment by DrBubbles42** [comment]
@charlieforward9 Ive gotten flutter set up for android studio and when I run flutter run after getting the dependencies I get an error saying 
`Package(s) mediapipe_genai require the native assets feature to be enabled. Enable using `flutter config --enable-native-assets`.`
when I run `flutter config --enable-native-assets` it sets the enable native assets to true and I can see it set to true if I run `flutter config --list`. If I run flutter run again it gives me the same error. Were you able to run it on your end?

**Comment by charlieforward9** [comment]
@DrBubbles42 I have not cloned the repo on my end for this, but I can look into doing that tomorrow. 

In the meantime, take a look in https://github.com/google/flutter-mediapipe/issues for leads.

Also, our flutter-mediapipe contact is @ **craiglabenz** . Keep this handle handy.

**Comment by charlieforward9** [comment]
See https://github.com/google/flutter-mediapipe/issues/64#issuecomment-2168380223

**Comment by DrBubbles42** [comment]
Finally got it to work on my phone with flutter. I had to alter some of the source for flutters get widget project to resolve some errors.
